name: Check CRLF

on: pull_request

jobs:
  Check-CRLF:
    name: workflow using the Check CRLF action
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v1

      - name: Use action to check for CRLF endings
        uses: erclu/check-crlf@v1